After CodeReview Fixes
DDonnyy/building_fixes pull request #2
Opened 2023-10-31 17:40 UTC by DDonnyy

-Added updating service in DB
-Added deleting useless buildings-points in DB

2023-11-01 17:24 UTC, kanootoko commented on check_buildings.py
> +    gdf_services = gpd.read_file(f"services_{city}.geojson")
gdf.read_file возвращает `Any`, и дальше по коду для gdf_services не выдаются подсказки (во всяком случае, в VS Code). Для упрощения жизни можно явным образом указывать тип, `gdf_services: gpd.GeoDataFrame = gpd.read_file(..)`

2023-11-01 17:24 UTC, kanootoko commented on check_buildings.py
> +    with open(os.path.join(os.getcwd(), "config.json"), encoding="UTF-8") as f:
> config.json

Когда выносишь какие-либо штуки в конфигурацию, старайся не только добавлять его в .gitignore (что уже супер), но и добавлять `config.example.json` или что-то в таком духе, где показана валидная структура конфига. Альтернативно, можно выносить описание конфигурации в README как код javascript (разница с json в данном случае в том, что в JS можно использовать комментарии, как:
```javascript
{
    // city name
    "city": "updated-city-name",
    // PostgreSQL DSN connection string
    "sqlConnection": "postgresql://user:password@host:5432/db_name",
    // distance in meters, if building-point is located in distance <= distance_limit to centroid of other building - merge
    "distance_limit": 30
}
```

2023-11-01 17:24 UTC, kanootoko commented on check_buildings.py
> +            f"\n{x[:3].to_string()}\n{'':-^60}"
pylint жалуется, что используется предварительная сборка строки для отправки в конфиг с помощью f-string'ов.
Казалось бы, f-string'и - наиболее быстрый способ создать необходимую строку с интерполяцией переменных (быстрее `str % (...)` и `str.format(...)`) - и это так. Однако, логгеру часто вообще не требуется проводить интерполяцию. Если, например, уровень логгирования установлен на `ERROR`, то методы `logger.warning` вообще не будут выполнять никакой логики, в том числе и подготовку строки.

2023-11-01 17:24 UTC, kanootoko commented on check_buildings.py
> +            f"\n{x[:3].to_string()}\n{'':-^60}"
Хотя конкретно здесь я не уверен, что здесь через сишное форматирование процентиками можно добиться `%-^60s` эффекта

2023-11-01 17:24 UTC, kanootoko commented on check_buildings.py
> +    save_cities_service_to_file(city, engine)
Несмотря на наличие логгирования, длительные операции никак не обозначаются - и после запуска на большом городе можно просто несколько минут смотреть на консоль и думать, все ли там в порядке.
Как минимум, можно писать о текущих операциях в `logger.info`, а как максимум, если какие-то операции бьются на отдельные куски (например, уже известно, что нужно удалить X зданий, и делать это предполагается последовательно по одной штуке в цикле), то можно использовать `tqdm`

2023-11-01 17:24 UTC, kanootoko commented on check_buildings.py
> +    remove_building_db(engine, gdf_geom_points)
Вот тут бы точно хотелось чтобы писались команды или результаты, или еще что-либо. Максимально юзер-френдли было бы выводить все команды на экран (можно в debug даже), а в конце приводить суммарные числа изменений (как "было удалено X зданий-точек, из них перенесено Y сервисов"), и спрашивать, сохранить ли изменения, или нет (если не поступает подтверждения - то откатывать транзакцию через `connection.rollback()` - но для этого нужно работать с одним соединением на протяжении всего main'а, а не отпарвлять в функции сам engine

2023-11-01 17:24 UTC, kanootoko commented on check_buildings.py
> +    try:
Такие try-finally можно более красиво заменять менеджером контекста: `with sql_alchemy_engine.connect() as connection:` - и тогда не нужно ничего закрывать самостоятельно

2023-11-01 17:24 UTC, kanootoko commented on check_buildings.py
> +        filename=os.path.join(os.getcwd(), log_file_name),
Лучше дублировать логи на консоль, используя два sink'а, раз уж используется логгирование

2023-11-01 17:24 UTC, kanootoko commented on check_buildings.py
> +        connection.close()
По-умолчанию, когда соединение закрывается, текущая транзакция откатывается. Для того, чтобы сохранить результаты работы, нужно явным образом делать `connection.commit()` в конце логического блока, когда ты хочешь, чтобы внесенные изменения остались в БД, даже если дальше что-то упадет (в пределах жизни соединения, конечно, потому что за ним уже все потеряется без коммита)

2023-11-01 17:24 UTC, kanootoko commented on check_buildings.py
> +            connection.execute(stmt)
В случае плохих зданий в не обновляемых активно городах хватает удалить только здания и физические объекты, но в общем случае стоит проверить и другие зависимости таблиц. Например, если здание было расселено, то его id есть в `social_stats.sex_age_social_houses.building_id` - и удалить здание без удаления записей с ним не выйдет, что выльется в ошибку и откат всех изменений.
Конкретно в случае текущей структуры, если просто расставить коммиты, то еще хуже: выполнится перенос сервисов (первый коммит), но здания останутся на месте (откат второй транзакции из-за ошибки).

2023-11-01 17:24 UTC, kanootoko commented on check_buildings.py
> +    gdf_services = gdf_services.query("physical_object_id in @list_buildings_points")
Не сталкивался с таким. Выглядит прикольно, но тот же pylint жалуется, что `list_buildings_points` не используется. И он прав формально, ведь ниже - просто текст. Я бы использовал явный `gdf_services = gdf_services[gdf_services["physical_object_id"].isin(list_buildings_points)]` , а сам лист можно так-то и множеством сделать, немного ускорив проверку наличия в нем идентификатора

2023-11-01 17:24 UTC, kanootoko commented on check_buildings.py
> +    t = datetime.now()
pylint передает, что переменная t не используется дальше

2023-11-06 12:44 UTC, kanootoko requested changes
Все еще не проверил на БД, так как запрос обновления не выполняется

2023-11-06 12:44 UTC, kanootoko commented on README.md
> +    "dry_run": false
Куски кода/конфигурации лучше оборачивать в тройные обратные кавычки с указанием диалекта.
Например,
```javascript
// comments are vaild in JS, not in JSON
{"a": "b"}
```

получается из
'''javascript
// comments are vaild in JS, not in JSON
{"a": "b"}
'''
, где вместо символа '  используется `

2023-11-06 12:44 UTC, kanootoko commented on building_fixes_example.log
Файл лога для примера - как-то даже избыточно, если и хочется, то можно его обрезать, оставив 3-5 зданий, так как идея строчек одинаковая, разные только id. Я бы еще и название города убрал в целом оставив просто что-то вроде `INFO Reasing <city_name>'s buildings file`

2023-11-06 12:44 UTC, kanootoko commented on check_buildings.py
> +            connection.commit()
Коммитить измененения в БД лучше после всего цикла, чтобы в случае ошибки не сохранилось ничего, и можно было полностью повторить эксперимент.
Исключения, конечно, тоже бывают - например, если операции в цикле довольно тяжелые, и можно прождать 5-10-15 минут, пока оно упадет с откатом транзакции. В этом случае можно использовать **чекпоинты** или просто коммиты раз в определенное количество обработанных итераций.

2023-11-06 12:44 UTC, kanootoko commented on README.md
> +    "dry_run": false
А, учитывая, что файл конфига представлен в качестве примера, то можно по-другому организовать эту часть. На файл дать явную ссылку, обернув `[The config.example.json]` в квадратные скобки, а в круглых сразу после этого прописав `(./config.example.json)`.
А сами атрибуты обычным списком описать, а не через си-подобные комментарии, как:
- `from_file` - If True, the files buildings_{city}.geojson and services_{city}.geojson should be present in the working directory, the `sqlConnection` parameter is not mandatory to fill in
- ...

2023-11-06 12:44 UTC, kanootoko commented on check_buildings.py
> +from tqdm import tqdm
`tqdm` подключен, но не используется дальше.
Можно использовать `tqdm.pandas()` для добавления DataFrame'ам (и GeoDataFrame как следствие) нового метода  `.progress_apply(...)`, чтобы на экран выводился прогресс прохода функции по датафрейму.
Ну, это логично использовать в длительных функциях, опять же, где у пользователя может возникнуть вопрос: "А сколько там еще остается?"

2023-11-06 12:44 UTC, kanootoko commented on check_buildings.py
> +    gdf_geom_points.loc[gdf_geom_points["closest_building_physical_id"].isnull()].apply(
1. В случае, когда не найдено ни одного плохого здания, выводится ложный warning с None-None-None параметрами. Этого можно избежать, если предварительно вызвать gdf_geom_points.drop_na(how='all')`
2. Видеть чиселки в логах - прикольно, но для дальнейшей обработки не очень удобно. Можно было бы сразу в случае наличия неопределившихся зданий выводить их building_id в json файл вывода в виде листа `[123, 124, 125]` (то есть нужно взять колонку building_id, преобразовать к листу и сохранить через `json.dump`), либо сразу id здания и физического объекта, либо двумя массивами (что лучше по спецификации json, так как не хранится массив вне объекта - `{"physical_objects_ids": [...], "buildings_ids": [...]`), либо массивом из объектов (что лучше в плане связности данных, `[{"physical_object_id": ..., "building_id": ...}, {...}]`)

2023-11-06 12:44 UTC, kanootoko commented on check_buildings.py
> +                sa.update("functional_objects")
На моей версии Алхимии (2.0.22) падает с тем, что ждет объект таблицы на вход `sa.update`. Таблица же должна быть собрана из всех колонок (как минимум используемых).
Здесь нужно либо заменить на sa.text с вызовом UPDATE и подстановкой параметров, либо создать все-таки схему БД до запуска. Второй вариант более запарный, но может потом пригодиться.
Классы таблиц SQLAlchemy можно сгенерировать через `sqlacodegen`

2023-11-06 12:51 UTC, DDonnyy commented on README.md
> +    "dry_run": false
![image](https://github.com/DDonnyy/building_fixes/assets/63115678/deb70a35-0dad-4147-b621-349eb2222671)

А как вот такое выделение делается?

2023-11-06 13:21 UTC, kanootoko commented on README.md
> +    "dry_run": false
Минус на строчке начинает ненумеровнный список, ровно как и любое число с точкой - нумерованный

2023-11-06 13:32 UTC, DDonnyy commented on README.md
> +    "dry_run": false
А я не про список, нашёл `code`))

2023-11-07 17:18 UTC, DDonnyy commented on check_buildings.py
> +                sa.update("functional_objects")
Выяснилось, что commit в случае context manager-a не надо, обновились все возможные сервисы Оренбурга без падений
```
    def upload_services_db(sql_alchemy_engine: sa.engine, data: gpd.GeoDataFrame):
        logging.info(f"Updating services in DB")
        with sql_alchemy_engine.connect() as connection:
            for ind, row in data.iterrows():
                id_value = row["id"]
                new_physical_object_id = row["physical_object_id"]
    
                stmt = (
                    sa.update(mapping.FunctionalObject)
                    .where(mapping.FunctionalObject.id == id_value)
                    .values(
                        physical_object_id=new_physical_object_id, updated_at=datetime.now()
                    )
                )
                connection.execute(stmt)
        logging.info("Done!\n")

2023-11-09 19:04 UTC, kanootoko commented on .gitignore
> +!config.example.json
Хммммм
Идея интересная, но есть ощущение, что так делать не хорошо в общем случае, чтобы нужно было включать каждый файл дополнительно при его добавлении. Конечно, что в одном, что в другом случае файлы в корне репозитория будут появляться не так уж и часто, но кажется, что "разрешение" на хранение кучи файлов в корне - это плохое решение, так как локально будет неудобно различать файлы, относящиеся к репозиторию от локальных вводов/выводов/etc.
Так что я бы просто подумал архитектурно, как оформить файлы, чтобы они не мешали коду.
Например по начальному состоянию файла есть ощущение, что входные данные (geojson) можно сложить в папку `input`, которую уже добавить в `.gitignore`, а выходные (geojson'ы, map.html, еще чего) - в `output`. Можно углубить дерево, добавив в input и output папки по городам, например. qgz с проектом тоже можно в разумное место разместить, или вне проекта в целом.

2023-11-09 19:04 UTC, kanootoko commented on README.md
> +This is a mini-utility for locating and removing building points from the ITMO IDU database,
Кстати, README.md обычно начинаются с параграфа первого уровня с названием проекта (`# check_buildings`). Понятно, что это в принципе просто скрипт изначально, но он уже начинает обрастать файлами (`mapping.py`)

2023-11-09 19:04 UTC, kanootoko commented on check_buildings.py
> +def download_buildings(city_name: str, sql_alchemy_engine: sa.engine, save: bool):
`sa.engine` - это модуль, аннотация `Engine`, она же `sa.Engine` была верной, и указывала на класс

2023-11-09 19:04 UTC, kanootoko commented on check_buildings.py
> +            gdf.to_file(f"buildings_{city_name}.geojson")
Вот здесь можно было бы сохранять в директорию `output/`, например, чтобы не захламлять корень. Или передавать вместо save путь до файла `str | None`, и `filename is None` трактовать как `save == False`, а строку - как имя файла для сохранения. Или вообще не добавлять логику сохранения в функцию получения GeoDataFrame'а.

2023-11-09 19:04 UTC, kanootoko commented on check_buildings.py
> +    logging.info("Done!\n")
Здесь процесс записи лога достаточно прямолинеен, но в целом можно выводить что-то вроде "Done downloading", чтобы было понятно, какой именно процесс завершился

2023-11-09 19:04 UTC, kanootoko commented on mapping.py
Интересно. А я и не смотрел, что `sqlacodegen` там нагенерил. Я всегда использовал только таблицы, определяемые как `t_table_name = Table(...)`, и думал, что `TableName(Base)` - это ORM'ное **дополнение** к нему. По текущему использованию я вижу, что оно точно такое же, как у меня раньше - но здесь нормально работает авто-дополнение по колонкам, и не нужно писать `t_table_name.t.column_name` вместо `TableName.column_name`. При этом для материализованных представлений создались только первые варианты. В общем, лично мне нужно будет разобраться в этом вопросе.
Хороший пример, что ревью полезно как автору, так и ревьюверу. Всегда можно увидеть вещи, которые раньше не замечал

2023-11-09 19:04 UTC, kanootoko commented on config.example.json
> +  "dry_run": false
Тут, кстати, встает вопрос разницы *настроек* и *конфигурации*. По идее, конфигурация - что-то, что пользователю если и нужно менять, то примерно один раз за продолжительное время пользования утилитой (либо несколько с подбором подходящих значений). В то время как настройки можно менять в конкретный момнет времени для получения необходимых результатов.
Ладно, может с настройками я загнул, а на деле имею в виду параметры и аргументы, не уверен.
В общем, кажется логичным вынести в конфиг DSN строку соединения с БД, `distance_limit` и, может быть, save_data. А вот `city` и `dry_run` выглядят как параметры, которые могут меняться от запуска к запуску, и было бы удобнее их указывать именно при запуске

2023-11-09 19:04 UTC, kanootoko commented on check_buildings.py
> +            connection.execute(stmt)
Здесь ничего не поменялось, оно все так же падает с `sqlalchemy.exc.ObjectNotExecutableError`

2023-11-09 19:04 UTC, kanootoko commented on check_buildings.py
> +            connection.execute(stmt)
И даже при замене на `stmt = sa.delete(mapping.Building).where(mapping.Building.id == building_id)` и `stmt = sa.delete(mapping.PhysicalObject).where(mapping.PhysicalObject.id == physical_object_id)` лучше не становится. Все-таки не все сервисы переносятся на другие здания:
```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) ОШИБКА:  UPDATE или DELETE в таблице "physical_objects" нарушает ограничение внешнего ключа "functional_objects_physical_object_fkey" таблицы "functional_objects"
DETAIL:  На ключ (id)=(*****) всё ещё есть ссылки в таблице "functional_objects".
```
Это запуск на локальном Оренбурге, если что

2023-11-09 19:04 UTC, kanootoko commented on check_buildings.py
> +            connection.execute(stmt)
А вот после добавления `conneciton.commit()` в конец `upload_services_db` у меня нормально отработало.
Так что у меня пока что вывод следующий, раз у тебя транзакция коммитится при выходе из контекстного менеджера:
1. Другая версия SQLAlchemy (у меня 2.0.22, напомню - но важно, что >= 2.0)
2. Другой драйвер под Алхимией, у меня `psycopg2`, и он пытается использоваться по-умолчанию, вроде как, если ты не указал в DSN строке по-другому

2023-11-09 19:16 UTC, DDonnyy commented on .gitignore
> +!config.example.json
Да, у меня там в папке лежит qgis проект со своими файлами и другой шлак, было удобно так сделать, в дальнейшем буду внимательнее подходить к  архитектуре!)

2023-11-29 09:59 UTC, merged