New mini-script
DDonnyy/building_fixes pull request #3
Opened 2023-11-29 16:02 UTC by DDonnyy

- Duplicated Services - new utility
- DB tools have been moved to a separate directory

2023-11-29 18:55 UTC, kanootoko requested changes

2023-11-29 18:55 UTC, kanootoko commented on DButility/dbTools.py
> +        logging.info(f"Successfully connected!")
Формально, engine имеет ленивую инициализацию, и из того, что объект создался, не следует, что подключение успешно. Да и по времени оно ничего не стоит, так что вторая запись в лог бессмысленна.
Впрочем, если хочется сделать настоящую проверку, то нужно обернуть запись во что-то вроде
```python
        try:
            with self.engine.connect() as conn:
                conn.execute(sa.text("SELECT 1")).scalar_one() == 1
            logging.info(f"Successfully connected!")
        except Exception:
            logging.error(...)
            sys.exit(1)
```

2023-11-29 18:55 UTC, kanootoko commented on DuplicatedServices/search_and_clear.py
> +    with open(os.path.join(os.getcwd(), "config.json"), encoding="UTF-8") as f:
На всякий случай отмечу, что `config.json` предполагается к наличию в текущей директории запуска. А если бы нужно было обращаться к конфигу, который лежит *в одной директории с исполняемым файлом*, то можно было бы взять полный путь до `__file__`, подняться в родителя, и к нему уже приджойнить "config.json"

2023-11-29 18:55 UTC, kanootoko commented on DuplicatedServices/search_and_clear.py
> +    log_file_name = f"search_and_clear.log"
Лишняя f-стринга

2023-11-29 18:55 UTC, kanootoko commented on DuplicatedServices/search_and_clear.py
> +    with open(os.path.join(os.getcwd(), "config.json"), encoding="UTF-8") as f:
При этом пример конфига лежит в файле с исполняемым файлом как раз, так что хочется туда же и реальный конфиг положить - а запуск осуществляется из общей директории (если без установки переменной среды `PYTHONPATH=..`)

2023-11-29 18:55 UTC, kanootoko commented on DuplicatedServices/search_and_clear.py
> +    ids = set(services_to_delete["functional_object_id"].tolist())
Интересно. У меня локально на dry-run упало здесь с `KeyError: 'functional_object_id'`, при этом сам DataFrame содержит 112 записей. И три колонки: `service_name  building_id city_service_type`

2023-11-29 18:55 UTC, kanootoko commented on DuplicatedServices/search_and_clear.py
> +        service_name = {df["city_service_type"][0]}
service_name внезапно стал множеством из одного элемента

2023-11-29 18:55 UTC, kanootoko commented on DButility/dbTools.py
> +    def remove_services(self, fuctional_object_ids: set):
Функциональной разницы нет, но скажу, что set может быть типизирован. Например, `set[int]`
Да и формально в данном случае это не обязан быть set, так как операции множества с ним не производятся. Я бы сказал, что тут нужно `fuctional_object_ids: Iterable[int]`, где Iterable из typing

2023-11-29 18:55 UTC, kanootoko commented on DButility/dbTools.py
> +from DButility import mapping
Как и в джаве, конвенция имен в Python говорит, что модули должны быть написаны snake_case'ом, а уже классы в них - CamelCase'ом.  Оно работает так и так, но просто непривычно видеть модуль, который называется с большой буквы

2023-11-29 18:55 UTC, kanootoko commented on DButility/dbTools.py
> +                    sa.select(sa.distinct(table.c.building_id))
Вместо `sa.distinct(table.c.building_id)` можно было написать `table.c.building_id.distinct()`
Опять же, разницы никакой формально, но как по мне, второе читается получше

2023-11-29 18:55 UTC, kanootoko commented on DButility/dbTools.py
> +                connection.execute(stmt)
Эта штука может легко упасть, если к физическому объекту привязан какой-нибудь сервис. В случае удаления здания нужно быть уверенным, что все его сервисы удалены (вот такие штуки можно выносить в докстринги) или же добавить сюда удаление явное зависимостей

2023-11-29 18:55 UTC, kanootoko commented on DButility/dbTools.py
> +            conn.execute(sa.text(f"REFRESH MATERIALIZED VIEW {name}"))
Коммит потерялся.
Вообще, вроде как для небольших операций с авто-коммитом, если не было exception'а, можно использовать `with self.engine.begin() as conn`

2023-11-29 18:55 UTC, kanootoko commented on DuplicatedServices/config.example.json
> +  "service_ids": [1,2,5,6,70]
Работать сразу с id'шниками удобно, но заполнять их - не очень. Когда есть возможность, я бы рарзешал вводить в поле `"service_types"` не только целые числа, но и строки: названия, коды, или все-таки id типов сервисов. А дальше перед обработкой объектов выбирал айдишники примерно как `SELECT id FROM  city_service_types WHERE id::varchar in :services OR name in :services OR code in :services`

2023-11-29 18:55 UTC, kanootoko commented on README.md
> +- `dry-run` - If true, found services will not be deleted.
В реальном конфиге, кстати, `dry_run` через подчеркивание, ниже - аналогично

2023-11-30 11:15 UTC, DDonnyy commented on DButility/dbTools.py
> +    def remove_services(self, fuctional_object_ids: set):
Ну была идея преобразовать в сет,чтобы все уникальные были айдишники, хотя на удалении это не скажется, с ошибкой вроде как не должен вылететь

2023-11-30 11:16 UTC, DDonnyy commented on DButility/dbTools.py
> +    def remove_services(self, fuctional_object_ids: set):
А, это про типизацию, понял!

2023-11-30 11:21 UTC, DDonnyy commented on DButility/dbTools.py
> +from DButility import mapping
Получается модуль должен быть  db_utility, а класс в нём DbWorker? А название файла? db_tools или DbTools?

2023-11-30 11:26 UTC, DDonnyy commented on DButility/dbTools.py
> +                connection.execute(stmt)
А как можно быстро получить все зависимости ?

2023-11-30 11:30 UTC, DDonnyy commented on DButility/dbTools.py
> +            conn.execute(sa.text(f"REFRESH MATERIALIZED VIEW {name}"))
![image](https://github.com/DDonnyy/building_fixes/assets/63115678/6812fd3a-7af0-4fc8-8b05-93b65fd65f93)

Угу, всё еще путаюсь

2023-11-30 19:32 UTC, kanootoko commented on DButility/dbTools.py
> +                connection.execute(stmt)
Я обычно просто делаю `\d table_name` в psql и смотрю на секцию "Ссылки извне":

![изображение](https://github.com/DDonnyy/building_fixes/assets/7778567/2a85f8be-7b2a-4e13-a4b1-e0aae98db2fc)

А так, ты ведь и находил скрипт: 
![изображение](https://github.com/DDonnyy/building_fixes/assets/7778567/00aae770-034f-478c-a3ea-8a733f6ed3c5)

2023-11-30 19:36 UTC, kanootoko commented on DButility/dbTools.py
> +from DButility import mapping
Наименования папок и файлов одинаково snake_case'ом, так как это все - путь до модуля с точки зрения python.
Так что да, db_utility.db_tools, а внутри - класс DbWorker (или DBWorker или DatabaseWorker, но worker с маленькой буквы читается не очень)

2023-12-21 11:59 UTC, merged